Solving ValueError: Classification metrics
So to solve the following error:
ValueError: Classification metrics can't handle a mix of binary and continuous targets

which the reason of that is the following line:
yhat_probs = yhat_probs[:, 0]

As the model outputs predicted probabilities, we need to transform them back to class labels before calculating the classification metrics.
So the new code is as follows:
yhat_probs = yhat_probs.flatten()
yhat_probs = np.where(yhat_probs > 0.5, 1, 0)