To solve ValueError: Classification metrics
Again to solve the following error:
ValueError: Classification metrics can't handle a mix of binary and continuous targets

which the reason of that is the following line:
yhat_probs1 = yhat_probs1[:, 0]

As the model outputs predicted probabilities, we need to transform them back to class labels before calculating the classification metrics.
So the new code is as follows:
yhat_probs1 = yhat_probs.flatten1()
yhat_probs1 = np.where(yhat_probs1 > 0.5, 1, 0)