To solve ValueError: Unknown layer: attention
To solve the following error:
ValueError: Unknown layer: attention. Please ensure this object is passed to the `custom_objects` argument.

While we are loading the saved model with attention layer we should give the customer layer definition to keras.models. So it can load the model with the customer attention layer that has been defined previously

So the code:
model1 = load_model('Save_Model_Attention.h5')

must change to this:
model1 = load_model('Save_Model_Attention.h5', custom_objects={"attention": attention})